### ISSUE TITLE
manage_home is defined but unused

### ISSUE THREAD

**Issue by aaronjcopley** [torrancew/puppet-account#35]
I was confused to see manage_home is defined but unused. This would be particularly useful for root_squash'd NFS mounted home directories. This module would fail to create $HOME/.ssh or correct permissions. I have implemented a fix if you are interested.

**Comment by aaronjcopley** [comment]
Sorry that took some months to send, but I put Puppet on the back-burner last Fall and am only now revisiting some things. I have submitted two PR.

**Comment by torrancew** [comment]
@aaronjcopley I had some similar issues -- still interested in getting this merged?

**Comment by torrancew** [comment]
Ok, I've looked this over and have a few thoughts:
  * I agree, there's a use case for not managing `$HOME`
  * I believe that, **if a user is trying to manage an SSH key**, it makes sense to manage the `$HOME/.ssh` directory

That is to say, that in my mind, `$manage_home = false` would ideally gate **only*** `$HOME` management, not `$HOME/.ssh` -- that should also be gate-able, but I'd propose it would be gated on the lack of SSH key management.

Thoughts?

**Comment by aaronjcopley** [comment]
I am not sure how I originally did it, but that makes sense to me. I haven't looked at it in some time. I will try to have a peak later today and possibly make adjustments.
