### ISSUE TITLE
Add one time password creation functionnality

### ISSUE THREAD

**Issue by nikolaiiii** [torrancew/puppet-account#42]
Hello, I would like to know if it is possible to add the ability to setup a password once, and then not to change as soon as it has been setup (for example if the user changes the password manually after its first login).

I was trying to did it directly in the manifest, based on this: http://www.joseftschiggerl.name/2012/11/create-users-with-puppet/

But since I know nothing in coding, I can't get it to work.
If you could tell me what to do, I can test it on my [Debian] server.

So far, this is what I added to the manifest file:
```
exec { "/bin/sed -i -e 's/$title:!:/$title:$password:/g' /etc/shadow":
            path => "/usr/bin:/usr/sbin:/bin",
            onlyif => "egrep -q '^${title}:[*!]:' /etc/shadow",
            require => User[$title]
    }
```

Thanks
Nicolas

**Comment by torrancew** [comment]
@nikolaiiii There are a few ways you can achieve this, but I'd be hesitant to put them into this module, as they tend to go against the typical puppet convention of managing *state*.

If you wanted to achieve this in role/profile code, and use in conjunction with this module, you could probably do one of a few things:
  * write a custom puppet type/provider that set a password only if it has no value, that inherits from the puppet `user` type. Name shadowing may allow it to "just work" with this module
  * drive the one-time setting via `sed` or perhaps `puppet resource` in an `exec`, and tie that to the `account` properly

Hope that helps!
