### ISSUE TITLE
Multiple ssh keys not handled

### ISSUE THREAD

**Issue by pythianali** [torrancew/puppet-account#43]
Hi,

I have a situation where I need to pass multiple ssh key values for specific users.   I attempted to use multiple ssh_key => line values in the configuration, one for each key that I wish to have for my user. 

The behavior of this is to use the key value on the last line and the others are ignored.

How would you envision implementing  this functionality with your module (if it is at all possible)?

**Comment by torrancew** [comment]
This has been released as part of v1.0.0 -- please feel free to open a new issue if you have any problems!
