### ISSUE TITLE
Problem module execution order

### ISSUE THREAD

**Issue by LeDistordu** [torrancew/puppet-account#50]
I have a problem not with module but with execution order... I have module "Zsh" and he must execute before this module "account". Can you help me ?

How insert "require class" in this module ?

**Comment by torrancew** [comment]
"require class" is only **one** (and not really the best, usually) way to get things done. Here are a few ways you could achieve this:

```
# manifests/site.pp
Account {
  require => Package['zsh'],
}
```

OR (per-account that uses zsh)

```
# wherever you declare an account
account { 'foo':
  shell   => 'zsh',
  require => Package['zsh'],
  ...
}
```

OR (if using create_resources)

```
# wherever you call create_resources
$accounts = hiera_hash('accounts', {})
create_resources('account', $accounts, {'require' => Package['zsh']})
```
