### ISSUE TITLE
Module Dead ??

### ISSUE THREAD

**Issue by smbambling** [torrancew/puppet-account#51]
I looks like there haven't been any updates in some time now.  I've forked a fork of this module that have a few of the pending PR applied. 

The project is here https://github.com/arineng/puppet-account.  I'd be happy to have user rebase and send PRs to us.

A more preferred method might to be transfer this project to the Puppet-Community to help with the current issues and PRs

https://github.com/puppet-community

**Comment by johnzimm** [comment]
I used to use this module, but have switched to this one:

https://forge.puppetlabs.com/camptocamp/accounts

torrancew-account worked well for what I needed but the camptocamp-accounts module fits my use case a bit better now.  Might be worth checking out.  There's a bit more activity there too.

**Comment by smbambling** [comment]
Yeah I looked at that module but you can't set a static UID/GID.

**Comment by johnzimm** [comment]
I am specifying UIDs right now.  And it looks like a pull request for GIDs was submitted yesterday: https://github.com/camptocamp/puppet-accounts/pull/20

**Comment by torrancew** [comment]
Let's say that this module was cryogenically frozen, but I'm thawing it out now.
