### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by TomyLobo** [torrancew/puppet-account#57]
Can you please create a new release on Puppet Forge?
I would like to use this module with Puppet 5.

Thanks in advance!

**Comment by torrancew** [comment]
@TomyLobo I started work over the last few weeks to do just that, and should have a release on the Forge in ~ a few days.

**Comment by torrancew** [comment]
It's also worth noting that the `develop` branch has this compatibility now, so if you're a Puppetfile user, you can easily test out the new version.

**Comment by torrancew** [comment]
I've just released v1.0.0 -- please open a new issue if you have any problems!

**Comment by TomyLobo** [comment]
Thanks, I just installed it, I'll let you know if I find something :)

Btw, puppet-cron also has ``"version_requirement": ">= 2.6.0 < 5.0.0"`` for puppet in its metadata.json.
I'm not yet far enough in my puppet upgrade to tell you whether that's the only thing that's blocking an update.

EDIT: looks like that isn't even a problem. I guess it's just informative.
